### ISSUE TITLE
Error with Symfony 5.0.2

### ISSUE THREAD

**Issue by alkemist** [isometriks/IsometriksSpamBundle#19] opened 2020-01-15 16:57 UTC
Attempted to call an undefined method named "root" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder".

**Comment by isometriks** [comment] 2020-01-17 03:37
What version are you using? It looks like this should be fixed: https://github.com/isometriks/IsometriksSpamBundle/blob/master/DependencyInjection/Configuration.php#L21

**Comment by tinowittig** [comment] 2020-02-15 23:25
at the moment the version 1.0.2 will be installed due the composer.json require section
the problem is the composer.json
`"symfony/form": "~3.0|~4.0"`
this should be changed to 
`"symfony/form": "~3.0|~4.0|~5.0"`

**Comment by isometriks** [comment] 2020-02-15 23:34
Ah, do you mind making a PR quick?

**Comment by tinowittig** [comment] 2020-02-15 23:44
there is still some other problems with the TranslatorInterface
i fixed it in a quick and dirty way for me: https://github.com/tinowittig/IsometriksSpamBundle
will check this next week if i have a solution for that and maybe will create a PR

**Comment by vitrus** [comment] 2020-07-25 11:38
Can confirm that this is still an issue with IsometriksSpamBundle `1.0.4` on Symfony 5.1
Using `"symfony/form": "~3.0|~4.0|~5.0"` in the projects composer.json does not fix the issue.

**Comment by isometriks** [comment] 2020-08-03 19:54
This should be all set now in 1.0.5

**Closed by isometriks** 2020-08-03 19:54 UTC
